version: '3.1'
services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    networks:
      - qdrant
    volumes:
      - qdrant2:/qdrant/storage:z
      - qdrant-tls2:/qdrant/tls:z
      - qdrant-config2:/qdrant/config:z
  

volumes:
  qdrant2:
    driver: local
    driver_opts:
      type: none
      device: "./data"
      o: bind
  qdrant-tls2:
    driver: local
    driver_opts:
      type: none
      device: "./tls"
      o: bind
  qdrant-config2:
    driver: local
    driver_opts:
      type: none
      device: "./config"
      o: bind


networks:
  qdrant:
    driver: bridge